# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer2.mydata.com:
  orderer3.mydata.com:
  orderer4.mydata.com:
  orderer5.mydata.com:

networks:
  mydata_platform:

services:

  orderer2.mydata.com:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    container_name: orderer2.mydata.com
    networks:
    - mydata_platform
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/mydata.com/orderers/orderer2.mydata.com/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/mydata.com/orderers/orderer2.mydata.com/tls/:/var/hyperledger/orderer/tls
        - orderer2.mydata.com:/var/hyperledger/production/orderer
    ports:
    - 8050:7050

  orderer3.mydata.com:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    container_name: orderer3.mydata.com
    networks:
    - mydata_platform
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/mydata.com/orderers/orderer3.mydata.com/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/mydata.com/orderers/orderer3.mydata.com/tls/:/var/hyperledger/orderer/tls
        - orderer3.mydata.com:/var/hyperledger/production/orderer
    ports:
    - 9050:7050

  orderer4.mydata.com:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    container_name: orderer4.mydata.com
    networks:
    - mydata_platform
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/mydata.com/orderers/orderer4.mydata.com/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/mydata.com/orderers/orderer4.mydata.com/tls/:/var/hyperledger/orderer/tls
        - orderer4.mydata.com:/var/hyperledger/production/orderer
    ports:
    - 10050:7050

  orderer5.mydata.com:
    extends:
      file: base/peer-base.yaml
      service: orderer-base
    container_name: orderer5.mydata.com
    networks:
    - mydata_platform
    volumes:
        - ./channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ./crypto-config/ordererOrganizations/mydata.com/orderers/orderer5.mydata.com/msp:/var/hyperledger/orderer/msp
        - ./crypto-config/ordererOrganizations/mydata.com/orderers/orderer5.mydata.com/tls/:/var/hyperledger/orderer/tls
        - orderer5.mydata.com:/var/hyperledger/production/orderer
    ports:
    - 11050:7050
